### ISSUE TITLE
Issues with Sketch

### ISSUE THREAD

**Issue by BzowK** [3KUdelta/ESP32_ServoClock_MST#1]
Good Morning!

I choose to use your build over the  as it's a cheaper option which seems to work just as well.  Unfortunately, I'm having two issues with your code...

## Issue 1 - 'resetFunc' was not declared in this scope ##

When attempting to verify just the original sketch you posted in IDE, I get the error above.  I added the following line above the function it's within and it verified afterwards.  Commenting out the line also verifies it, but sure it's there for a reason :)  Bringing it up as don't know if related to the 2nd issue.

    void(* resetFunc) (void) = 0; //declare reset function @ address 0

## Issue 2 - Sketch Not Working *(wdt reset)* ##
Once the above issue was addressed, I uploaded it to an NodeMCU and opened Serial Monitor.  Once up, the following was echoed and repeated every few seconds:

     ets Jan  8 2013,rst cause:4, boot mode:(3,6)
    wdt reset
    load 0x4010f000, len 1392, room 16 
    tail 0
    chksum 0xd0
    csum 0xd0
    v3d128e5c
    ~ld

I've researched for at least an hour so far and found that its a watchdog reset, but don't know how to resolve it.  If it makes a difference, I have nothing connected to NodeMCU pins - it's just plugged into the PC via USB.  Some of the suggestions mention code issues, reducing long delays, & to pin assignments being incorrect.  Was hoping you could provide suggestions if not replicate.

*To note, the exact hardware I'm using is a KeeYees 3pcs ESP8266 NodeMCU CP2102 ESP-12E - a model I've never had issues with before and the pins match the ones in your diagram.*

Any suggestions or thoughts?  Thanks!

**Comment by BzowK** [comment]
Think I got it working (I hope).  Basically replaced using the WiFi.h library with ESP8266WiFi.h then changed a couple other things to match.  Hopefully servo stuff works, too :)  Thanks

**Comment by 3KUdelta** [comment]
Hi, happy to see that it works.
